server {
    listen 80;
    root /usr/share/nginx/html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location = /assets/mf-registry.json {
        add_header Content-Type application/json;
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }
}